- id: "cmake-format:0.4.5"
  name: cmake-format v0.4.5
  description: cmake-format can format your listfiles nicely so that they don't look like crap.
  entry: cmake-format
  language: python
  types: [file, text]
  files: '(CMakeLists\.txt|\.cmake|\.cmake\.in)$'

